apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: privnet
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              privnet: "true"
  podSelector:
    matchLabels:
      privnet: "true"
