apiVersion: v1
kind: Service
metadata:
  name: amf
spec:
  type: ClusterIP
  ports:
  - name: free5gc-amf
    port: 29518
    protocol: TCP
    targetPort: 29518
  - name: if-n2
    port: 38412
    protocol: SCTP
    targetPort: 38412
