apiVersion: v1
kind: Service
metadata:
  name: free5gc-amf
  labels:
    app: free5gc-amf
spec:
  type: ClusterIP
  ports:
  - name: free5gc-amf
    port: 29518
    protocol: TCP
    targetPort: 29518
  - name: if-n1n2
    port: 38412
    protocol: SCTP
    targetPort: 38412
  selector:
    app: free5gc-amf
