apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-amf
  labels:
    app: free5gc-amf
    sliceidx: 6d3d79da-f781-4cd9-813a-dbdad01e01c0
  annotations:
    free5gc.org/nssi-id: '27394d25-dbf5-428e-8fc3-f5b2add67115'
    free5gc.org/nsi-ids: '[
        { "id": "4e6db941-47d6-4fce-9c71-f7eb35a75d03" },
    ]'
    free5gc.org/supported-snssais: '[
        { "st": 1,
          "ssd": "010203",
        },
        { "st": 1,
          "ssd": "112233",
        },
    ]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: free5gc-amf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: free5gc-amf
      annotations:
        k8s.v1.cni.cncf.io/networks: free5gc-amf-n1n2
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: free5gc-amf
        image: succassion/free5gc-amf
        imagePullPolicy: IfNotPresent
        #securityContext:
          #privileged: false
        command: ["/bin/sh", "-ec"]
        args: ["sleep 5 && ./amf -amfcfg ../config/amfcfg.yaml"]
        ports:
        - name: free5gc-amf
          containerPort: 29518
          protocol: TCP
        - name: if-n1n2
          containerPort: 38412
          protocol: SCTP
        env:
        - name: GIN_MODE
          value: release
        volumeMounts:
        - mountPath: /free5gc/config/amfcfg.yaml
          name: amfcfg
          subPath: amfcfg.yaml
        - mountPath: /free5gc/config/free5gc.yaml
          name: free5gc
          subPath: free5gc.yaml
      volumes:
      - name: amfcfg
        configMap:
          name: free5gc-amf-configmap
          items:
          - key: amfcfg.yaml
            path: amfcfg.yaml
      - name: free5gc
        configMap:
          name: free5gc-amf-configmap
          items:
          - key: free5gc.yaml
            path: free5gc.yaml
