namespace: free5gc-k8s
namePrefix: free5gc-
commonLabels:
  app: free5gc-amf
resources: 
  - free5gc-amf-configmap.yaml
  - free5gc-amf-service.yaml
  - free5gc-amf-cni.yaml
  - free5gc-amf-deployment.yaml
