apiVersion: v1
kind: Service
metadata:
  labels:
    app: free5gc-upf1
  name: free5gc-upf1
spec:
  selector:
    app: free5gc-upf1
  ports:
  - name: free5gc-upf1-n3
    port: 2152
    protocol: UDP
    targetPort: 2152
  - name: free5gc-upf1-n4
    port: 8805
    protocol: UDP
    targetPort: 8805
