apiVersion: apps/v1
kind: Deployment
metadata:
  name: udr
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: free5gc-udr
        image: succassion/free5gc-udr
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-ec"]
        args: ["sleep 5 && ./udr -udrcfg ../config/udrcfg.yaml"]
        ports:
        - name: free5gc-udr
          containerPort: 29504
          protocol: TCP
        env:
        - name: GIN_MODE
          value: release
        resources:
          requests:
            memory: "32Mi"
            cpu: "150m"
          limits:
            memory: "32Mi"
            cpu: "150m"
        volumeMounts:
        - mountPath: /free5gc/config/udrcfg.yaml
          name: udrcfg
          subPath: udrcfg.yaml
      volumes:
        - name: udrcfg
          configMap:
            name: free5gc-udr-configmap
            items:
            - key: udrcfg.yaml
              path: udrcfg.yaml
