apiVersion: v1
kind: Service
metadata:
  name: free5gc-udr
  labels:
    app: free5gc-udr
spec:
  type: ClusterIP
  ports:
    - name: free5gc-udr
      port: 29504
      protocol: TCP
      targetPort: 29504
  selector:
    app: free5gc-udr
