apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-n6dummy
  labels:
    app: free5gc-n6dummy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: free5gc-n6dummy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: free5gc-n6dummy
      annotations:
        k8s.v1.cni.cncf.io/networks: free5gc-n6dummy-n6
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - name: free5gc-n6dummy
          image: docker.io/centos/tools:latest
          imagePullPolicy: IfNotPresent
          command:
          - /sbin/init
          #securityContext:
            #privileged: true
