apiVersion: apps/v1
kind: Deployment
metadata:
  name: n6dummy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: free5gc-n6dummy-n6
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: free5gc-n6dummy
        image: docker.io/centos/tools:latest
        imagePullPolicy: IfNotPresent
        #securityContext:
        #  privileged: true
        command:
        - /sbin/init
        resources:
          requests:
            memory: "16Mi"
            cpu: "100m"
          limits:
            memory: "16Mi"
            cpu: "100m"

