apiVersion: v1
kind: Service
metadata:
  name: free5gc-nssf
  labels:
    app: free5gc-nssf
spec:
  type: ClusterIP
  ports:
    - name: free5gc-nssf
      port: 29531
      protocol: TCP
      targetPort: 29531
  selector:
    app: free5gc-nssf
