apiVersion: apps/v1
kind: Deployment
metadata:
  name: nssf
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: free5gc-nssf
        image: succassion/free5gc-nssf
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-ec"]
        args: ["sleep 10 && ./nssf -nssfcfg ../config/nssfcfg.yaml"]
        ports:
        - containerPort: 29531
          name: free5gc-nssf
          protocol: TCP
        env:
        - name: GIN_MODE
          value: release
        resources:
          requests:
            memory: "32Mi"
            cpu: "150m"
          limits:
            memory: "32Mi"
            cpu: "150m"
        volumeMounts:
        - mountPath: /free5gc/config/nssfcfg.yaml
          name: nssfcfg
          subPath: nssfcfg.yaml
      volumes:
      - name: nssfcfg
        configMap:
          name: free5gc-nssf-configmap
          items:
          - key: nssfcfg.yaml
            path: nssfcfg.yaml
