---
apiVersion: v1
kind: Service
metadata:
  name: free5gc-mongodb-service
  labels:
    name: free5gc-mongodb
spec:
  type: ClusterIP
  ports:
  - name: free5gc-mongodb
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: free5gc-mongodb
