kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: free5gc-mongodb-pvc
  labels:
    app: free5gc-mongodb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
