apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-ausf
  labels:
    app: free5gc-ausf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: free5gc-ausf
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: free5gc-ausf
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: free5gc-amf
        image: succassion/free5gc-ausf
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-ec"]
        args: ["sleep 5 && ./ausf -ausfcfg ../config/ausfcfg.yaml"]
        ports:
        - name: free5gc-ausf
          containerPort: 29509
          protocol: TCP
        env:
        - name: GIN_MODE
          value: release
        resources:
          requests:
            memory: "32Mi"
            cpu: "150m"
          limits:
            memory: "32Mi"
            cpu: "150m"
        volumeMounts:
        - mountPath: /free5gc/config/ausfcfg.yaml
          name: ausfcfg
          subPath: ausfcfg.yaml
      volumes:
      - name: ausfcfg
        configMap:
          name: free5gc-ausf-configmap
          items:
          - key: ausfcfg.yaml
            path: ausfcfg.yaml
