apiVersion: v1
kind: Service
metadata:
  name: free5gc-ausf
  labels:
    app: free5gc-ausf
spec:
  type: ClusterIP
  ports:
  - name: free5gc-ausf
    port: 29509
    protocol: TCP
    targetPort: 29509
  selector:
    app: free5gc-ausf
