apiVersion: v1
kind: Service
metadata:
  name: udm
spec:
  type: ClusterIP
  ports:
    - name: free5gc-udm
      port: 29503
      protocol: TCP
      targetPort: 29503
  selector:
    app: free5gc-udm
