apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-udm
  labels:
    app: free5gc-udm
  annotations:
    free5gc.org/nssi-id: '27394d25-dbf5-428e-8fc3-f5b2add67115'
    free5gc.org/nsi-ids: '[
        { "id": "4e6db941-47d6-4fce-9c71-f7eb35a75d03" },
    ]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: free5gc-udm
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: free5gc-udm
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: free5gc-udm
        image: succassion/free5gc-udm
        imagePullPolicy: IfNotPresent
        #securityContext:
          #privileged: false
        command: ["/bin/sh", "-ec"]
        args: ["sleep 5 && ./udm -udmcfg ../config/udmcfg.yaml"]
        ports:
        - containerPort: 29503
          name: free5gc-udm
          protocol: TCP
        env:
        - name: GIN_MODE
          value: release
        volumeMounts:
        - mountPath: /free5gc/config/udmcfg.yaml
          name: udmcfg
          subPath: udmcfg.yaml
        - mountPath: /free5gc/config/free5gc.yaml
          name: free5gc
          subPath: free5gc.yaml
      volumes:
      - name: udmcfg
        configMap:
          name: free5gc-udm-configmap
          items:
          - key: udmcfg.yaml
            path: udmcfg.yaml
      - name: free5gc
        configMap:
          name: free5gc-udm-configmap
          items:
          - key: free5gc.yaml
            path: free5gc.yaml
