apiVersion: apps/v1
kind: Deployment
metadata:
  name: udm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: free5gc-udm
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: free5gc-udm
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: free5gc-udm
        image: succassion/free5gc-udm
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-ec"]
        args: ["sleep 5 && ./udm -udmcfg ../config/udmcfg.yaml"]
        ports:
        - containerPort: 29503
          name: free5gc-udm
          protocol: TCP
        env:
        - name: GIN_MODE
          value: release
        resources:
          requests:
            memory: "32Mi"
            cpu: "150m"
          limits:
            memory: "32Mi"
            cpu: "150m"
        volumeMounts:
        - mountPath: /free5gc/config/udmcfg.yaml
          name: udmcfg
          subPath: udmcfg.yaml
      volumes:
      - name: udmcfg
        configMap:
          name: free5gc-udm-configmap
          items:
          - key: udmcfg.yaml
            path: udmcfg.yaml
