apiVersion: v1
kind: ConfigMap
metadata:
  name: free5gc-nrf-configmap
data:
  free5gc.yaml: |
    db_uri: mongodb://free5gc-mongodb:27017/free5GC

    # the kind of log output
    # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
    # ReportCaller: enable the caller report or not, value: true or false
    NRF:
      debugLevel: info
      ReportCaller: true
    PathUtil:
      debugLevel: info
      ReportCaller: true
    OpenApi:
      debugLevel: info
      ReportCaller: true
    MongoDBLibrary:
      debugLevel: info
      ReportCaller: true

  nrfcfg.yaml: |
    info:
      version: 1.0.0
      description: NRF initial local configuration

    configuration:
      MongoDBName: free5gc # database name in MongoDB
      MongoDBUrl: mongodb://free5gc-mongodb:27017 # a valid URL of the mongodb
      sbi: # Service-based interface information
        scheme: http # the protocol for sbi (http or https)
        registerIPv4: free5gc-nrf #nrf.free5gc.org # IP used to serve NFs or register to another NRF
        bindingIPv4: 0.0.0.0 #nrf.free5gc.org  # IP used to bind the service
        port: 29510 #8000 # port used to bind the service
      DefaultPlmnId:
        mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
      serviceNameList: # the SBI services provided by this NRF, refer to TS 29.510
        - nnrf-nfm # Nnrf_NFManagement service
        - nnrf-disc # Nnrf_NFDiscovery service
