apiVersion: v1
kind: Service
metadata:
  name: nrf
spec:
  type: ClusterIP
  selector:
    app: free5gc-nrf
  ports:
    - name: free5gc-nrf
      port: 29510
      protocol: TCP
      targetPort: 29510
