apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-nrf
  labels:
    app: free5gc-nrf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: free5gc-nrf
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: free5gc-nrf
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: free5gc-nrf
        image: succassion/free5gc-nrf
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-ec"]
        args: ["sleep 5 && ./nrf -nrfcfg ../config/nrfcfg.yaml"]
        ports:
        - name: free5gc-nrf
          containerPort: 29510
          protocol: TCP
        env:
        - name: GIN_MODE
          value: release
        resources:
          requests:
            memory: "32Mi"
            cpu: "150m"
          limits:
            memory: "32Mi"
            cpu: "150m"
        volumeMounts:
        - mountPath: /free5gc/config/nrfcfg.yaml
          name: nrfcfg
          subPath: nrfcfg.yaml
      volumes:
      - name: nrfcfg
        configMap:
          name: free5gc-nrf-configmap
          items:
          - key: nrfcfg.yaml
            path: nrfcfg.yaml
