apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-nrf
  labels:
    app: free5gc-nrf
  annotations:
    free5gc.org/nssi-id: '27394d25-dbf5-428e-8fc3-f5b2add67115'
    free5gc.org/nsi-ids: '[
        { "id": "4e6db941-47d6-4fce-9c71-f7eb35a75d03" },
    ]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: free5gc-nrf
  template:
    metadata:
      labels:
        app: free5gc-nrf
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: free5gc-nrf
        image: succassion/free5gc-nrf
        imagePullPolicy: IfNotPresent
        #securityContext:
          #privileged: false
        command: ["/bin/sh", "-ec"]
        args: ["sleep 5 && ./nrf -nrfcfg ../config/nrfcfg.yaml"]
        ports:
        - name: free5gc-nrf
          containerPort: 29510
          protocol: TCP
        env:
        - name: GIN_MODE
          value: release
        volumeMounts:
        - mountPath: /free5gc/config/nrfcfg.yaml
          name: nrfcfg
          subPath: nrfcfg.yaml
        - mountPath: /free5gc/config/free5gc.yaml
          name: free5gc
          subPath: free5gc.yaml
      volumes:
      - name: nrfcfg
        configMap:
          name: free5gc-nrf-configmap
          items:
          - key: nrfcfg.yaml
            path: nrfcfg.yaml
      - name: free5gc
        configMap:
          name: free5gc-nrf-configmap
          items:
          - key: free5gc.yaml
            path: free5gc.yaml
