apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: free5gc-mongodb
  replicas: 1
  template:
    spec:
      containers:
      - name: mongodb
        image: mongo:4.2.7
        ports:
        - name: mongodb
          containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: free5gc-mongodb-config
              key: mongo_initdb_database
