apiVersion: v1
kind: ConfigMap
metadata:
  name: free5gc-udr-configmap
data:
  udrcfg.conf: |
    info:
      version: 1.0.0
      description: UDR initial local configuration

    configuration:
      sbi: # Service-based interface information
        scheme: http # the protocol for sbi (http or https)
        registerIPv4: udr.free5gc.org # IP used to register to NRF
        bindingIPv4: udr.free5gc.org  # IP used to bind the service
        port: 8000 # port used to bind the service
      mongodb:
        name: free5gc # Database name in MongoDB
        url: mongodb://db:27017 # URL of MongoDB
      nrfUri: http://nrf.free5gc.org:8000 # a valid URI of NRF
