apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-udr
  labels:
    app: free5gc-udr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: free5gc-udr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: free5gc-udr
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: free5gc-udr
        image: succassion/free5gc-compose_free5gc-udr
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
        command: ["/bin/sh", "-ec"]
        args: ["sleep 5 && ./udr -udrcfg ../config/udrcfg.yaml"]
        ports:
        - name: free5gc-udr
          containerPort: 29504
          protocol: TCP
        volumeMounts:
        - mountPath: /free5gc/config/udrcfg.yaml
          name: udrcfg
          subPath: udrcfg.yaml
        - mountPath: /free5gc/config/free5gc.yaml
          name: free5gc
          subPath: free5gc.yaml
      volumes:
        - name: udrcfg
          configMap:
            name: free5gc-udr-configmap
            items:
            - key: udrcfg.yaml
              path: udrcfg.yaml
        - name: free5gc
          configMap:
            name: free5gc-udr-configmap
            items:
            - key: free5gc.yaml
              path: free5gc.yaml
