apiVersion: v1
kind: ConfigMap
metadata:
  name: free5gc-upf-configmap
data:
  free5gc.yaml: |
    UPF:
      # the kind of log output
      # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
      # ReportCaller: enable the caller report or not, value: true or false
      debugLebel: info
      ReportCaller: false
 
  upfcfg.yaml: |
    info:
      version: 1.0.0
      description: UPF configuration

    configuration:
      pfcp:
        - addr: 172.16.30.30 #upf1.free5gc.org

      gtpu:
        - addr: 192.168.10.20 #upf1.free5gc.org
        # [optional] gtpu.name
        #   - name: upf.5gc.nctu.me
        # [optional] gtpu.ifname
        # - ifname: gtpif

      dnn_list:
        - dnn: internet
          cidr: 60.60.0.0/24
          # [optional] apn_list[*].natifname
          # natifname: eth0
        - dnn: internet2
          cidr: 10.10.0.0/24
          # [optional] apn_list[*].natifname
          # natifname: eth0

  upfipset.sh: |
    #!/bin/sh
    ### UPF IPtables forwarding rules configuration

    iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    iptables -I FORWARD 1 -j ACCEPT
    iptables -t nat -A POSTROUTING -o upfgtp -j MASQUERADE
