apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-upfb
  labels:
    app: free5gc-upfb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: free5gc-upfb
  template:
    metadata:
      labels:
        app: free5gc-upfb
      annotations:
        k8s.v1.cni.cncf.io/networks: free5gc-upf-n3, free5gc-upf-n4, free5gc-upf-n6
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: free5gc-upfb
        image: succassion/free5gc-compose_free5gc-upf-b
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
          capabilities:
              add: ["NET_ADMIN", "NET_RAW", "NET_BIND_SERVICE", "SYS_TIME"]
        command: ["/bin/sh", "-ec"]
        args: ["sleep 5 && ../config/upfipset.sh && ./free5gc-upfd -f ../config/upfcfg.yaml"]
        ports:
        - name: if-n3
          containerPort: 2152
          protocol: UDP
        - name: if-n4
          containerPort: 8805
          protocol: UDP
        volumeMounts:
        - mountPath: /free5gc/config/upfcfg.yaml
          name: upfcfg
          subPath: upfcfg.yaml
        - mountPath: /free5gc/config/free5gc.yaml
          name: free5gc
          subPath: free5gc.yaml
        - mountPath: /free5gc/config/upfipset.sh
          name: upfipset
          readOnly: true
          subPath: upfipset.sh    
        - mountPath: /dev/net/tun
          name: tun-dev
      volumes:
      - name: upfcfg
        configMap:
          name: free5gc-upf-configmap
          items:
          - key: upfcfg.yaml
            path: upfcfg.yaml
      - name: free5gc
        configMap:
          name: free5gc-upf-configmap
          items:
          - key: free5gc.yaml
            path: free5gc.yaml
      - name: upfipset
        configMap:
          name: free5gc-upf-configmap
          defaultMode: 0700
          items:
          - key: upfipset.sh
            path: upfipset.sh
      - name: tun-dev
        hostPath:
          path: /dev/net/tun
