apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-nssf
  labels:
    app: free5gc-nssf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: free5gc-nssf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: free5gc-nssf
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: free5gc-nssf
        image: succassion/free5gc-compose_free5gc-nssf
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
        command: ["/bin/sh", "-ec"]
        args: ["sleep 10 && ./nssf -nssfcfg ../config/nssfcfg.yaml"]
        ports:
        - containerPort: 29531
          name: free5gc-nssf
          protocol: TCP
        volumeMounts:
        - mountPath: /free5gc/config/nssfcfg.yaml
          name: nssfcfg
          subPath: nssfcfg.yaml
        - mountPath: /free5gc/config/free5gc.yaml
          name: free5gc
          subPath: free5gc.yaml
      volumes:
      - name: nssfcfg
        configMap:
          name: free5gc-nssf-configmap
          items:
          - key: nssfcfg.yaml
            path: nssfcfg.yaml
      - name: free5gc
        configMap:
          name: free5gc-nssf-configmap
          items:
          - key: free5gc.yaml
            path: free5gc.yaml

