---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-webui
  labels:
    app: free5gc-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: free5gc-webui
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: free5gc-webui
    spec:
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: free5gc-webui
        image: succassion/free5gc-compose_free5gc-webui
        imagePullPolicy: IfNotPresent
        command: ["./webui"]
        ports:
        - name: free5gc-webui
          containerPort: 5000
          protocol: TCP
        volumeMounts:
        - mountPath: /free5gc/config/webuicfg.yaml
          name: webuicfg
          subPath: webuicfg.yaml
        - mountPath: /free5gc/config/free5gc.yaml
          name: free5gc
          subPath: free5gc.yaml
      volumes:
      - name: webuicfg
        configMap:
          name: free5gc-webui-configmap
          items:
          - key: webuicfg.yaml
            path: webuicfg.yaml
      - name: free5gc
        configMap:
          name: free5gc-webui-configmap
          items:
          - key: free5gc.yaml
            path: free5gc.yaml
