apiVersion: v1
kind: ConfigMap
metadata:
  name: free5gc-upf2-configmap
data:
  free5gc.yaml: |
    UPF:
      # the kind of log output
      # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
      # ReportCaller: enable the caller report or not, value: true or false
      debugLebel: info
      ReportCaller: true
 
  upfcfg.yaml: |
    info:
      version: 1.0.0
      description: UPF configuration

    configuration:
      pfcp:
        - addr: 172.16.30.32 #upf1.free5gc.org

      gtpu:
        - addr: 192.168.10.22 #upf1.free5gc.org
        # [optional] gtpu.name
        #   - name: upf.5gc.nctu.me
        # [optional] gtpu.ifname
        # - ifname: gtpif

      dnn_list:
        - dnn: internet
          cidr: 60.60.0.0/16
          # [optional] apn_list[*].natifname
          # natifname: eth0
        - dnn: internet2
          cidr: 10.10.0.0/16
          # [optional] apn_list[*].natifname
          # natifname: eth0
