apiVersion: v1
kind: ConfigMap
metadata: 
  name: free5gc-webui-configmap
data:
  free5gc.yaml: |
    # webui
    WEBUI:
      # the kind of log output
      # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
      # ReportCaller: enable the caller report or not, value: true or false
      debugLevel: info
      ReportCaller: true

  webuicfg.yaml: |
    info:
      version: 1.0.0
      description: WebUI initial local configuration

    configuration:
      mongodb: # the mongodb connected by this webui
        name: free5gc # name of the mongodb
        url: mongodb://free5gc-mongodb:27017 # a valid URL of the mongodb
