---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-webui
  labels:
    app: free5gc-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: free5gc-webui
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: free5gc-webui
    spec:
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: free5gc-webui
        image: succassion/free5gc-webui
        imagePullPolicy: IfNotPresent
        command: ["./webui"]
        ports:
        - name: free5gc-webui
          containerPort: 5000
          protocol: TCP
        env:
        - name: GIN_MODE
          value: release
        resources:
          requests:
            memory: "16Mi"
            cpu: "100m"
          limits:
            memory: "16Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: /free5gc/config/webuicfg.yaml
          name: webuicfg
          subPath: webuicfg.yaml
      volumes:
      - name: webuicfg
        configMap:
          name: free5gc-webui-configmap
          items:
          - key: webuicfg.yaml
            path: webuicfg.yaml
