apiVersion: v1
kind: Service
metadata:
  name: pcf
spec:
  type: ClusterIP
  ports:
    - name: free5gc-pcf
      port: 29507
      protocol: TCP
      targetPort: 29507
  selector:
    app: free5gc-pcf
