apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcf
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: free5gc-pcf
        image: succassion/free5gc-pcf
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-ec"]
        args: ["sleep 5 && ./pcf -pcfcfg ../config/pcfcfg.yaml"]
        ports:
        - name: free5gc-pcf
          containerPort: 29507
          protocol: TCP
        env:
        - name: GIN_MODE
          value: release
        resources:
          requests:
            memory: "32Mi"
            cpu: "150m"
          limits:
            memory: "32Mi"
            cpu: "150m"
        volumeMounts:
        - mountPath: /free5gc/config/pcfcfg.yaml
          name: pcfcfg
          subPath: pcfcfg.yaml
      volumes:
        - name: pcfcfg
          configMap:
            name: free5gc-pcf-configmap
            items:
            - key: pcfcfg.yaml
              path: pcfcfg.yaml
