apiVersion: v1
kind: Service
metadata:
  name: smf
spec:
  type: ClusterIP
  ports:
  - name: free5gc-smf-sbi
    port: 29502
    protocol: TCP
    targetPort: 29502
  - name: free5gc-smf-n4
    port: 8805
    protocol: UDP
    targetPort: 8805
  selector:
    app: free5gc-smf
