apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-smf
  labels:
    app: free5gc-smf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: free5gc-smf
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: free5gc-smf
      annotations:
        k8s.v1.cni.cncf.io/networks: free5gc-smf-n4
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: free5gc-smf
        image: succassion/free5gc-smf
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-ec"]
        args: ["sleep 5 && ./smf -smfcfg ../config/smfcfg.yaml -uerouting ../config/uerouting.yaml"]
        ports:
        - name: if-sbi
          containerPort: 29502
          protocol: TCP
        - name: if-n4
          containerPort: 8805
          protocol: UDP
        env:
        - name: GIN_MODE
          value: release
        resources:
          requests:
            memory: "32Mi"
            cpu: "150m"
          limits:
            memory: "32Mi"
            cpu: "150m"
        volumeMounts:
        - mountPath: /free5gc/config/smfcfg.yaml
          name: smfcfg
          subPath: smfcfg.yaml
        - mountPath: /free5gc/config/uerouting.yaml
          name: uerouting
          subPath: uerouting.yaml
      volumes:
        - name: smfcfg
          configMap:
            name: free5gc-smf-configmap
            items:
            - key: smfcfg.yaml
              path: smfcfg.yaml
        - name: uerouting
          configMap:
            name: free5gc-smf-configmap
            items:
            - key: uerouting.yaml
              path: uerouting.yaml
